### ISSUE TITLE
KVRestore EOFException for com.android.chrome

### ISSUE THREAD

**Issue by grote** [seedvault-app/seedvault#182]
```
12-18 04:58:07.064  6312  6559 I RestoreCoordinator: Next restore package!
12-18 04:58:07.280  6312  6559 I RestoreCoordinator: Found K/V data for com.android.chrome.
12-18 04:58:07.281  1607  4456 I BackupManagerService: Next restore package: RestoreDescription{com.android.chrome : KEY_VALUE}
12-18 04:58:07.285  1607  4456 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10185; state: DISABLED
12-18 04:58:07.285  1607  4456 D BackupManagerService: [UserID:0] awaiting agent for ApplicationInfo{9d950a1 com.android.chrome}
12-18 04:58:07.286  1607  1728 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10185; state: ENABLED
12-18 04:58:07.296   874   874 D Zygote  : Forked child process 7540
12-18 04:58:07.298  1607  1728 I ActivityManager: Start proc 7540:com.android.chrome/u0a185 for backup {com.android.chrome/org.chromium.chrome.browser.ChromeBackupAgent}
12-18 04:58:07.309  1194  1223 I adbd    : jdwp connection from 7540
12-18 04:58:07.345  7540  7540 W .android.chrom: JIT profile information will not be recorded: profile file does not exist.
12-18 04:58:07.354  7540  7540 D NetworkSecurityConfig: Using Network Security Config from resource 0_resource_name_obfuscated debugBuild: false
12-18 04:58:07.405  1607  3676 D BackupManagerService: [UserID:0] agentConnected pkg=com.android.chrome agent=android.os.BinderProxy@826a411
12-18 04:58:07.405  1607  4456 I BackupManagerService: [UserID:0] got agent android.app.IBackupAgent$Stub$Proxy@4973976
12-18 04:58:07.405  1607  4456 D BackupManagerService: initiateOneRestore packageName=com.android.chrome
12-18 04:58:07.606  7260  7260 I         : [K][PM] power PM Statistic start (12-18 04:58:07)
12-18 04:58:07.606  7260  7260 I [K] wakeup_source: 'a600000.ssusb'
12-18 04:58:07.607  7260  7260 I rpmh_master_stat: APSS(776,sleep:59s) MPSS(762,sleep:561s) ADSP(32615,sleep:465s) ADSP_ISLAND(13181,sleep:268s) CDSP(113,sleep:653s)
12-18 04:58:07.607  7260  7260 I msm_rpmstats_stats_dump: (aosd,0,sleep:0s) (cxsd,0,sleep:0s) (ddr ,0,sleep:0s)
12-18 04:58:07.607  7260  7260 I         : [K][PM] power PM Statistic done
12-18 04:58:07.355  7540  7540 D NetworkSecurityConfig: Using Network Security Config from resource 0_resource_name_obfuscated debugBuild: false
12-18 04:58:08.052  6312  7122 V KVRestore:   getRestoreData() found 16 key files
12-18 04:58:08.425  6312  7122 V KVRestore:     ... key=AndroidDefault.BANDWIDTH_REDUCTION_PROXY_ENABLED size=1
12-18 04:58:08.722   918  1007 D VSC     : @ 670.021: [WO] tilt angle 89
12-18 04:58:08.841  6312  7122 V KVRestore:     ... key=AndroidDefault.first_run_flow size=1
12-18 04:58:09.301  6312  7122 V KVRestore:     ... key=AndroidDefault.first_run_signin_setup size=1
12-18 04:58:09.671  6312  7122 V KVRestore:     ... key=AndroidDefault.first_run_tos_accepted size=1
12-18 04:58:10.041  6312  7122 E KVRestore: Unable to read backup records
12-18 04:58:10.041  6312  7122 E KVRestore: java.io.IOException: java.io.EOFException
12-18 04:58:10.041  6312  7122 E KVRestore:     at com.stevesoltys.seedvault.crypto.CryptoImpl.decryptMultipleSegments(Crypto.kt:185)
12-18 04:58:10.041  6312  7122 E KVRestore:     at com.stevesoltys.seedvault.transport.restore.KVRestore.readAndWriteValue(KVRestore.kt:150)
12-18 04:58:10.041  6312  7122 E KVRestore:     at com.stevesoltys.seedvault.transport.restore.KVRestore.getRestoreData(KVRestore.kt:90)
12-18 04:58:10.041  6312  7122 E KVRestore:     at com.stevesoltys.seedvault.transport.restore.RestoreCoordinator.getRestoreData(RestoreCoordinator.kt:228)
12-18 04:58:10.041  6312  7122 E KVRestore:     at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$getRestoreData$1.invokeSuspend(ConfigurableBackupTransport.kt:220)
12-18 04:58:10.041  6312  7122 E KVRestore:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-18 04:58:10.041  6312  7122 E KVRestore:     at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
12-18 04:58:10.041  6312  7122 E KVRestore:     at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
12-18 04:58:10.041  6312  7122 E KVRestore:     at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
12-18 04:58:10.041  6312  7122 E KVRestore:     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
12-18 04:58:10.041  6312  7122 E KVRestore:     at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
12-18 04:58:10.041  6312  7122 E KVRestore:     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
12-18 04:58:10.041  6312  7122 E KVRestore:     at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
12-18 04:58:10.041  6312  7122 E KVRestore:     at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.getRestoreData(ConfigurableBackupTransport.kt:219)
12-18 04:58:10.041  6312  7122 E KVRestore:     at android.app.backup.BackupTransport$TransportImpl.getRestoreData(BackupTransport.java:739)
12-18 04:58:10.041  6312  7122 E KVRestore:     at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:706)
12-18 04:58:10.041  6312  7122 E KVRestore:     at android.os.Binder.execTransactInternal(Binder.java:1159)
12-18 04:58:10.041  6312  7122 E KVRestore:     at android.os.Binder.execTransact(Binder.java:1123)
12-18 04:58:10.041  6312  7122 E KVRestore: Caused by: java.io.EOFException
12-18 04:58:10.041  6312  7122 E KVRestore:     at com.stevesoltys.seedvault.header.HeaderReaderImpl.readSegmentHeader(HeaderReader.kt:65)
12-18 04:58:10.041  6312  7122 E KVRestore:     at com.stevesoltys.seedvault.crypto.CryptoImpl.decryptSegment(Crypto.kt:193)
12-18 04:58:10.041  6312  7122 E KVRestore:     at com.stevesoltys.seedvault.crypto.CryptoImpl.decryptMultipleSegments(Crypto.kt:183)
12-18 04:58:10.041  6312  7122 E KVRestore:     ... 17 more
12-18 04:58:10.041  1607  4456 E BackupManagerService: Error getting restore data for com.android.chrome
12-18 04:58:10.042  6312  7124 D RestoreCoordinator: finishRestore
12-18 04:58:10.042  6312  7124 I FullRestore: Finish restore of com.android.onetimeinitializer!
12-18 04:58:10.043  6312  7124 I FullRestore: Resetting state.
```

**Comment by grote** [comment]
I copied this stacktrace from the log posted to https://github.com/seedvault-app/seedvault/issues/152#issuecomment-748131676
@Uldiniad is it possible that the chrome file got truncated somehow when you were manually copying over data?

**Comment by Uldiniad** [comment]
possible yeah, can't confirm without trying again and performing checksums though?

**Comment by chirayudesai** [comment]
Huh, I thought chrome didn't support backup (`allowBackup=false`)
