### ISSUE TITLE
Permission denial after choosing backup folder

### ISSUE THREAD

**Issue by skrimix** [seedvault-app/seedvault#247]
I'm trying to install Seedvault as standalone app on AOSP-based custom rom, for this I made magisk module. The app and two xml files install fine, but after I choose backup folder in DocumentsUI an error message is shown: "Unable to get the permission to write to the backup location."
Logcat shows these errors:
```
05-03 16:51:23.308 20168 20168 E com.stevesoltys.seedvault.ui.storage.StorageActivity: OpenDocumentTree: content://com.android.externalstorage.documents/tree/primary%3ASeedVault
05-03 16:51:23.320 19526 19556 E DatabaseUtils: Writing exception to parcel
05-03 16:51:23.320 19526 19556 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/root from pid=20168, uid=10162 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
05-03 16:51:23.320 19526 19556 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
05-03 16:51:23.320 19526 19556 E DatabaseUtils: 	at com.android.externalstorage.ExternalStorageProvider.enforceReadPermissionInner(ExternalStorageProvider.java:147)
05-03 16:51:23.320 19526 19556 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
05-03 16:51:23.320 19526 19556 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
05-03 16:51:23.320 19526 19556 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
05-03 16:51:23.320 19526 19556 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
05-03 16:51:23.320 19526 19556 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1123)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: Failed to load some roots from com.android.externalstorage.documents
05-03 16:51:23.321 20168 20168 W StorageRootResolver: java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/root from pid=20168, uid=10162 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.os.Parcel.createException(Parcel.java:2357)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.os.Parcel.readException(Parcel.java:2340)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.content.ContentResolver.query(ContentResolver.java:1183)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.content.ContentResolver.query(ContentResolver.java:1115)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.content.ContentResolver.query(ContentResolver.java:1071)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at com.stevesoltys.seedvault.ui.storage.StorageRootResolver.getStorageRoots(StorageRootResolver.kt:30)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at com.stevesoltys.seedvault.ui.storage.StorageActivity$openDocumentTree$1.onActivityResult(StorageActivity.kt:37)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at com.stevesoltys.seedvault.ui.storage.StorageActivity$openDocumentTree$1.onActivityResult(StorageActivity.kt:25)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:325)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:289)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:577)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:128)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.app.Activity.dispatchActivityResult(Activity.java:8310)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5002)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.os.Looper.loop(Looper.java:223)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at java.lang.reflect.Method.invoke(Native Method)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
05-03 16:51:23.321 20168 20168 W StorageRootResolver: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by grote** [comment]
I have no idea about this and it is not really a supported use-case, but try not giving it the `android.permission.MANAGE_DOCUMENTS` permission and see if this changes things.

**Comment by skrimix** [comment]
Removing MANAGE_DOCUMENTS permisson (if that's what you meant) didn't change anything. I got around this issue by changing the code a bit - ignored storage root query failure and hardcoded values that depend on it (root.title, root.isUsb, root.requiresNetwork). Isn't a proper fix, but did the trick for me, and maybe will give you an idea on how this can be fixed
