### ISSUE TITLE
Crash in background

### ISSUE THREAD

**Issue by opusforlife2** [seedvault-app/seedvault#257]
I have Scoop running in the background at all times to catch crashes, and I noticed it had a Seedvault crash. I have no context for this crash. It happened automatically while I was not interacting with the device. I'm on LOS 17.1 with Seedvault baked in.

This is the crash log. I hope it is useful:
```
FATAL EXCEPTION: Binder:30094_9
Process: com.stevesoltys.seedvault, PID: 30094
java.lang.AssertionError
	at com.stevesoltys.seedvault.transport.backup.FullBackup.performFullBackup(FullBackup.kt:100)
	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.performFullBackup(BackupCoordinator.kt:222)
	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$performFullBackup$1.invokeSuspend(ConfigurableBackupTransport.kt:128)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.performFullBackup(ConfigurableBackupTransport.kt:127)
	at android.app.backup.BackupTransport$TransportImpl.performFullBackup(BackupTransport.java:745)
	at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:745)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by grote** [comment]
Thanks a lot.

We are told to perform a backup, but [haven't cleaned up our state from last time](https://github.com/seedvault-app/seedvault/blob/d53f0fcde2202b79f83d7b77817e1face6c98e13/app/src/main/java/com/stevesoltys/seedvault/transport/backup/FullBackup.kt#L100). It would be great to somehow get more log context here, so we can find out *why* this is happening.

**Comment by opusforlife2** [comment]
How would I go about that? Should I try manually initiating a backup while capturing a log?

**Comment by grote** [comment]
I suspect that it won't happen again simply by manually starting a backup. If it would, we'd have already seen this. There must be some special undocumented circumstances I would expect. But you can give it a try.

Ideally, when Scoop catches a crash, it saves the entire logcat buffer. Maybe it could do that? This would be ideal for debugging.

**Comment by opusforlife2** [comment]
@TacoTheDank Possible?

**Comment by TacoTheDank** [comment]
@opusforlife2 Yeah, I think it's feasible. I don't really have an idea on how to go about doing it though, since there's certain things with Android I don't really understand all that well. Contributions are always appreciated! :)

For now, it might be easier to obtain the logcat buffer by debugging seedvault with ADB logcat.

**Comment by opusforlife2** [comment]
@TacoTheDank Alright. Thanks!

**Comment by opusforlife2** [comment]
This is what I got when I opened the logcat fairly quickly after a crash. It doesn't seem to have any useful info either:

```
06-24 04:28:36.667 E/AndroidRuntime(14261): Process: com.stevesoltys.seedvault, PID: 14261
06-24 04:28:36.667 E/AndroidRuntime(14261): 	at com.stevesoltys.seedvault.transport.backup.FullBackup.performFullBackup(FullBackup.kt:100)
06-24 04:28:36.667 E/AndroidRuntime(14261): 	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.performFullBackup(BackupCoordinator.kt:222)
06-24 04:28:36.667 E/AndroidRuntime(14261): 	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$performFullBackup$1.invokeSuspend(ConfigurableBackupTransport.kt:128)
06-24 04:28:36.667 E/AndroidRuntime(14261): 	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.performFullBackup(ConfigurableBackupTransport.kt:127)
06-24 05:53:00.154 I/ActivityManager(1269): Killing 14647:com.stevesoltys.seedvault/u0a68 (adj 975): empty #17
```

**Comment by grote** [comment]
> It doesn't seem to have any useful info either:

Yeah that's not so useful. I would be interested in anything that was above these lines so I can try to understand how it get into this unexpected state.

**Comment by opusforlife2** [comment]
Any idea what to look for? Is there another system app it interacts with or something?

**Comment by grote** [comment]
Seedvault is called by the system itself via an under documented API. In your case, it is calling it in an unexpected way, so ideally, we get a full log. If there's privacy concerns, I can also receive it privately and only extract what we need and then delete it.

**Comment by opusforlife2** [comment]
Alright. The next time I'm able to catch it fast enough, I'll save the entire log and send it.

**Comment by opusforlife2** [comment]
Any progress in debugging this issue from your side? Sadly, Seedvault always seems to run at odd hours, which means it's always too late to do anything when I come across a crash report in Scoop. So I'm not closer to capturing useful logs yet.

**Comment by opusforlife2** [comment]
I got the exact same crash again. The ones I reported earlier were from LOS 17.1, this one has occurred for the first time on LOS 19.1. Same device. I don't know if any relevant Seedvault code has changed in the meanwhile. Just adding this for completeness's sake.

Here are some different lines from the general log. Since the app crashed, searching using the PID didn't work. This is by searching for "seedvault":

```
11-14 03:45:41.290 I/ActivityManager( 1384): Process com.stevesoltys.seedvault (pid 15300) has died: cch+65 CEM
11-14 03:52:37.225 I/ActivityManager( 1384): com.stevesoltys.seedvault is exempt from freezer
11-14 03:52:37.262 I/ActivityManager( 1384): Start proc 20927:com.stevesoltys.seedvault/u0a111 for service {com.stevesoltys.seedvault/com.stevesoltys.seedvault.transport.ConfigurableBackupTransportService}
11-14 04:55:01.283 I/ActivityManager( 1384): Process com.stevesoltys.seedvault (pid 20927) has died: cch+65 CEM
```

**Comment by grote** [comment]
@opusforlife2 this log doesn't help. Ideally, we need the full log, because for non-devs it is difficult to filter relevant parts. Searching for seedvault won't do it.

**Comment by opusforlife2** [comment]
Oh. Okay. Hope I'll get lucky next time and encounter the crash ASAP after it occurs. :/
