### ISSUE TITLE
Backup provider not shown in menu after backup restore (with [broken?] [adoptable?] storage)

### ISSUE THREAD

**Issue by rugk** [seedvault-app/seedvault#307]
## STR

I needed to follow [these steps](https://github.com/seedvault-app/seedvault/issues/85#issuecomment-692974249) and ended up using Nextcloud for restoration as that was the only good option.

It did also work somewhat (did nor restore any settings, similar to #296), but I was fine with that as I could just configure them manually/anyway did already while it was restored.

A reboot did not work.
I use an external SD card formatted as "adopted storage" that always takes some seconds at startup until it is detected. Just in case that matters.

Grepped logcat:
```
grep -E "seedvault|SeedVault" --context=15 ~/Downloads/logcat.txt
08-28 10:47:01.750  3475  3502 I LatinIME:LogUtils: Dictionary info: dictionary = main:de ; version = 54 ; date = 1414726263
08-28 10:47:02.121  1827  2767 I chatty  : uid=10144(com.android.systemui) pool-5-thread-5 expire 1 line
08-28 10:47:02.249  1290  3124 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 1000; state: DISABLED
08-28 10:47:02.272   670   670 D Zygote  : Forked child process 3506
08-28 10:47:02.275  1290  1493 I ActivityManager: Start proc 3506:com.android.localtransport/1000 for service {com.android.localtransport/com.android.localtransport.LocalTransportService}
08-28 10:47:02.311   969   987 I adbd    : jdwp connection from 3506
08-28 10:47:02.364  3506  3506 I .localtranspor: The ClassLoaderContext is a special shared library.
08-28 10:47:02.377  3506  3506 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-28 10:47:02.378  3506  3506 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-28 10:47:02.391  1290  1290 I TransportClient: LocalTransportService#0: Notifying [TransportManager.registerTransport()] transport = IBackupTransport
08-28 10:47:02.398  1290  3124 D BackupTransportManager: Transport com.android.localtransport/.LocalTransportService registered
08-28 10:47:02.398  1290  3124 D BackupManagerService: [UserID:0] Transport com.android.localtransport/.LocalTransport registered 3184ms after first request (delay = 3000ms)
08-28 10:47:02.414  1290  3124 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10092; state: DISABLED
08-28 10:47:02.415  1290  1493 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10092; state: ENABLED
08-28 10:47:02.432   670   670 D Zygote  : Forked child process 3529
08-28 10:47:02.435  1290  1493 I ActivityManager: Start proc 3529:com.stevesoltys.seedvault/u0a92 for service {com.stevesoltys.seedvault/com.stevesoltys.seedvault.transport.ConfigurableBackupTransportService}
08-28 10:47:02.449  3529  3529 F zygote64: jni_internal.cc:729] JNI FatalError called: (com.stevesoltys.seedvault) frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:795: Failed to mount tmpfs to /mnt/expand/2484f4fd-7758-4d04-9e4a-d77a886098f3/user: No such file or directory
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655] Runtime aborting...
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655] Dumping all threads without mutator lock held
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655] All threads:
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655] DALVIK THREADS (1):
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655] "main" prio=5 tid=1 Runnable
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x72499568 self=0x7a31c9fbe0
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655]   | sysTid=670 nice=0 cgrp=default sched=0/0 handle=0x7b5859c4f8
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655]   | state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655]   | stack=0x7ff1570000-0x7ff1572000 stackSize=8192KB
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655]   | held mutexes= "abort lock" "mutator lock"(shared held)
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655]   native: (backtrace::Unwind failed for thread 670: Thread doesn't exist)
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655]   at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native method)
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655]   at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:344)
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteConnection.processOneCommand(ZygoteConnection.java:257)
08-28 10:47:02.485  3529  3529 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteServer.runSelectLoop(ZygoteServer.java:550)
--
08-28 10:47:12.354  1290  1958 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10140?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
08-28 10:47:12.355  3852  3878 W MessagingApp: canonicalizeMccMnc: invalid mccmnc:null ,null
08-28 10:47:12.363  3852  3878 I MessagingApp: Carrier configs loaded: Bundle[{httpSocketTimeout=60000, aliasMinChars=2, smsToMmsTextThreshold=-1, enableSMSDeliveryReports=true, maxMessageTextSize=-1, supportMmsContentDisposition=true, enabledTransID=false, aliasEnabled=false, supportHttpCharsetHeader=false, allowAttachAudio=true, smsToMmsTextLengthThreshold=-1, recipientLimit=2147483647, uaProfTagName=x-wap-profile, aliasMaxChars=48, maxImageHeight=1944, enableMMSDeliveryReports=false, userAgent=, mmsCloseConnection=false, config_cellBroadcastAppLinks=true, maxSubjectLength=40, httpParams=, enableGroupMms=true, emailGatewayNumber=, maxMessageSize=614400, naiSuffix=, enableMMSReadReports=false, maxImageWidth=2592, uaProfUrl=, enabledMMS=true, enabledNotifyWapMMSC=false, sendMultipartSmsAsSeparateMessages=false, enableMultipartSMS=true}] from resources+system for subId=1
08-28 10:47:12.385  3852  3881 I MessagingAppDataModel: Fixup: Send failed - 0 Download failed - 0
08-28 10:47:12.396   670   670 D Zygote  : Forked child process 3883
08-28 10:47:12.400  3852  3879 W MessagingApp: canonicalizeMccMnc: invalid mccmnc:null ,null
08-28 10:47:12.407  3852  3879 I MessagingApp: Carrier configs loaded: Bundle[{httpSocketTimeout=60000, aliasMinChars=2, smsToMmsTextThreshold=-1, enableSMSDeliveryReports=true, maxMessageTextSize=-1, supportMmsContentDisposition=true, enabledTransID=false, aliasEnabled=false, supportHttpCharsetHeader=false, allowAttachAudio=true, smsToMmsTextLengthThreshold=-1, recipientLimit=2147483647, uaProfTagName=x-wap-profile, aliasMaxChars=48, maxImageHeight=1944, enableMMSDeliveryReports=false, userAgent=, mmsCloseConnection=false, config_cellBroadcastAppLinks=true, maxSubjectLength=40, httpParams=, enableGroupMms=true, emailGatewayNumber=, maxMessageSize=614400, naiSuffix=, enableMMSReadReports=false, maxImageWidth=2592, uaProfUrl=, enabledMMS=true, enabledNotifyWapMMSC=false, sendMultipartSmsAsSeparateMessages=false, enableMultipartSMS=true}] from resources+system for subId=1
08-28 10:47:12.408  1290  1493 W ActivityManager: Slow operation: 58ms so far, now at startProcess: returned from zygote!
08-28 10:47:12.408  1290  1493 W ActivityManager: Slow operation: 59ms so far, now at startProcess: done updating battery stats
08-28 10:47:12.409  1290  1493 W ActivityManager: Slow operation: 59ms so far, now at startProcess: building log message
08-28 10:47:12.409  1290  1493 I ActivityManager: Start proc 3883:com.android.onetimeinitializer/u0a121 for broadcast {com.android.onetimeinitializer/com.android.onetimeinitializer.OneTimeInitializerReceiver}
08-28 10:47:12.409  1290  1493 W ActivityManager: Slow operation: 59ms so far, now at startProcess: starting to update pids map
08-28 10:47:12.409  1290  1493 W ActivityManager: Slow operation: 59ms so far, now at startProcess: done updating pids map
08-28 10:47:12.426  3852  3881 I MessagingAppDataModel: ProcessPendingMessagesAction: Start queueing for subId 1
08-28 10:47:12.433  3702  3718 W System  : A resource failed to call close. 
08-28 10:47:12.436  1290  1492 W ActivityManager: Process ProcessRecord{3f75314 3529:com.stevesoltys.seedvault/u0a92} failed to attach
08-28 10:47:12.436  1290  1492 W ActivityManager: Forcing bringing down service: ServiceRecord{4d39d32 u0 com.stevesoltys.seedvault/.transport.ConfigurableBackupTransportService}
08-28 10:47:12.437  1290  1492 I ActivityManager: Killing 3529:com.stevesoltys.seedvault/u0a92 (adj -10000): start timeout
08-28 10:47:12.437  1290  1290 E TransportClient: ConfigurableBackupTransportService#1: Binding died: client UNUSABLE
08-28 10:47:12.440  1290  1290 I TransportClient: ConfigurableBackupTransportService#1: Notifying [TransportManager.registerTransport()] transport = null
08-28 10:47:12.442  1290  3124 E TransportClient: ConfigurableBackupTransportService#1: [TransportManager.registerTransport()] Transport connection failed
08-28 10:47:12.446  1290  3124 E BackupTransportManager: Couldn't connect to transport com.stevesoltys.seedvault/.transport.ConfigurableBackupTransportService for registration
08-28 10:47:12.456   969   987 I adbd    : jdwp connection from 3883
08-28 10:47:12.469  3852  3880 E MessagingApp: PhoneUtils.getValidE164Number(): Not able to parse phone number Redacted-0 for country DE
08-28 10:47:12.475  1290  3124 I BackupManagerService: [UserID:0] Found stale backup journal, scheduling
08-28 10:47:12.486   670   670 I Zygote  : Process 3013 exited due to signal 9 (Killed)
08-28 10:47:12.489  3852  3881 I MessagingAppDataModel: ProcessPendingMessagesAction: No messages to send or download
08-28 10:47:12.494  1290  3124 I chatty  : uid=1000(system) backup-0 identical 39 lines
08-28 10:47:12.494  1290  3124 I BackupManagerService: [UserID:0] Found stale backup journal, scheduling
08-28 10:47:12.536  3883  3883 I timeinitialize: The ClassLoaderContext is a special shared library.
08-28 10:47:12.562  3883  3883 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-28 10:47:12.564  3883  3883 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-28 10:47:12.567  3883  3883 V OneTimeInitializerReceiver: OneTimeInitializerReceiver.onReceive
08-28 10:47:12.583  3852  3879 I MessagingAppDataModel: SyncMessagesAction: Starting batch for messages from 1630138817727 to 1630140432300 (message update limit = 80, message scan limit = 4000)
08-28 10:47:12.585  1290  1958 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10091; state: DISABLED
08-28 10:47:12.587  1290  1493 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10091; state: ENABLED
08-28 10:47:12.587  1290  1958 I ActivityManager: Killing 3232:com.android.keychain/1000 (adj 975): empty #17
--
08-28 10:47:25.341  2153  2153 D AssistGesture: mAssistOnly:false, isSupported:false, isSensorAvailable:false
08-28 10:47:25.343  1290  1958 I SystemUpdateManagerService: No existing info file /data/system/system-update-info.xml
08-28 10:47:25.344  2153  2153 D SysUpdatePrefContr: Update statue unknown
08-28 10:47:25.351  2153  4364 D SettingsActivity: No enabled state changed, skipping updateCategory call
08-28 10:47:25.395  4065  4131 D InstalledAppProviderSer: insertAppIntoDb com.google.android.gms
08-28 10:47:25.418  2153  2153 D ControllerRendererPool: Controller is already there.
08-28 10:47:25.419  1290  1491 I ActivityTaskManager: Displayed com.android.settings/.SubSettings: +245ms
08-28 10:47:25.420  1290  1491 I ActivityTaskManager: Fully drawn com.android.settings/.SubSettings: +245ms
08-28 10:47:25.440  4065  4131 D InstalledAppProviderSer: insertAppIntoDb com.google.android.gsf
08-28 10:47:25.473  4065  4131 D InstalledAppProviderSer: insertAppIntoDb com.qti.qualcomm.datastatusnotification
08-28 10:47:25.494  4065  4131 D InstalledAppProviderSer: insertAppIntoDb com.qualcomm.qcrilmsgtunnel
08-28 10:47:25.517  4065  4131 D InstalledAppProviderSer: insertAppIntoDb com.qualcomm.qti.cne
08-28 10:47:25.541  4065  4131 D InstalledAppProviderSer: insertAppIntoDb com.qualcomm.qti.telephonyservice
08-28 10:47:25.567  4065  4131 D InstalledAppProviderSer: insertAppIntoDb com.qualcomm.timeservice
08-28 10:47:25.600  4065  4131 D InstalledAppProviderSer: insertAppIntoDb com.qualcomm.wfd.service
08-28 10:47:25.714  4065  4131 D InstalledAppProviderSer: insertAppIntoDb com.stevesoltys.seedvault
08-28 10:47:25.736   792   792 I android.hardware.power-service-qti: Power setMode: 5 to: 0
08-28 10:47:25.744  4065  4131 D InstalledAppProviderSer: insertAppIntoDb lineageos.platform
08-28 10:47:25.779  4065  4131 D InstalledAppProviderSer: insertAppIntoDb org.calyxos.backup.contacts
08-28 10:47:25.820  4065  4131 D InstalledAppProviderSer: insertAppIntoDb org.codeaurora.ims
08-28 10:47:25.849  4065  4131 D InstalledAppProviderSer: insertAppIntoDb org.fdroid.fdroid.privileged
08-28 10:47:25.885  1290  3174 I ActivityManager: Killing 3883:com.android.onetimeinitializer/u0a121 (adj 985): empty #17
08-28 10:47:25.910  4065  4131 D InstalledAppProviderSer: insertAppIntoDb org.lineageos.audiofx
08-28 10:47:25.979   670   670 I Zygote  : Process 3883 exited due to signal 9 (Killed)
08-28 10:47:25.999  4065  4131 D InstalledAppProviderSer: insertAppIntoDb org.lineageos.backgrounds
08-28 10:47:26.016  1290  1500 I libprocessgroup: Successfully killed process cgroup uid 10121 pid 3883 in 129ms
08-28 10:47:26.031  4065  4131 D InstalledAppProviderSer: insertAppIntoDb org.lineageos.customization
08-28 10:47:26.123  4065  4131 D InstalledAppProviderSer: insertAppIntoDb org.lineageos.eleven
08-28 10:47:26.182  4065  4131 D InstalledAppProviderSer: insertAppIntoDb org.lineageos.etar
08-28 10:47:26.234  4065  4131 D InstalledAppProviderSer: insertAppIntoDb org.lineageos.jelly
08-28 10:47:26.323  4065  4131 D InstalledAppProviderSer: insertAppIntoDb org.lineageos.lineageparts
--
08-28 10:54:11.153  4185  4255 D NetworkUtils: Searching known-servers store at /data/user/0/com.nextcloud.client/files/knownServers.bks
08-28 10:54:12.779  4185  4255 D OfflineSyncJob: /: enter
08-28 10:54:12.818  4185  4255 D OfflineSyncJob: /: currentEtag: 
08-28 10:54:12.849  4185  4255 D OwnCloudClient #0: Creating OwnCloudClient
08-28 10:54:12.850  4185  4255 D AccountUtils: Restoring cookies for **USER**@**SERVER**
08-28 10:54:12.852  4185  4255 D AccountUtils: Restoring cookies for **USER**@**SERVER**
08-28 10:54:12.873  4185  4255 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
08-28 10:54:12.873  4185  4255 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
08-28 10:54:12.873  4185  4255 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
08-28 10:54:12.925  4185  4255 D OwnCloudClient #0: REQUEST PROPFIND /remote.php/webdav/
08-28 10:54:12.929  4185  4255 D AdvancedSslSocketFactory: Creating SSL Socket with remote **SERVER**:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@9a0fe90
08-28 10:54:12.930  4185  4255 D AdvancedSslSocketFactory:  ... with connection timeout 5000 and socket timeout 40000
08-28 10:54:12.932  4185  4255 I ServerNameIndicator: SSLSocket implementation: org.conscrypt.Java8EngineSocket
08-28 10:54:12.933  4185  4255 I ServerNameIndicator: SNI done, hostname: **SERVER**
08-28 10:54:14.374  4185  4255 D OfflineSyncJob: /: eTag changed
08-28 10:54:14.436  4185  4255 D OfflineSyncJob: /.SeedVaultAndroidBackup/: enter
08-28 10:54:14.507  4185  4255 D OfflineSyncJob: /.SeedVaultAndroidBackup/: currentEtag: 
08-28 10:54:14.520  4185  4255 D OwnCloudClient #0: REQUEST PROPFIND /remote.php/webdav/.SeedVaultAndroidBackup/
08-28 10:54:14.733  4185  4255 D OfflineSyncJob: /.SeedVaultAndroidBackup/: eTag unchanged
08-28 10:54:14.734  4185  4255 E OfflineSyncJob: Failed to update etag on /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/**USER**@**SERVER**
08-28 10:54:14.734  4185  4255 E OfflineSyncJob: java.lang.RuntimeException: Accessing result data after operation failed!
08-28 10:54:14.734  4185  4255 E OfflineSyncJob: 	at com.owncloud.android.lib.common.operations.RemoteOperationResult.getData(RemoteOperationResult.java:514)
08-28 10:54:14.734  4185  4255 E OfflineSyncJob: 	at com.nextcloud.client.jobs.OfflineSyncWork.recursive(OfflineSyncWork.kt:131)
08-28 10:54:14.734  4185  4255 E OfflineSyncJob: 	at com.nextcloud.client.jobs.OfflineSyncWork.doWork(OfflineSyncWork.kt:68)
08-28 10:54:14.734  4185  4255 E OfflineSyncJob: 	at androidx.work.Worker$1.run(Worker.java:85)
08-28 10:54:14.734  4185  4255 E OfflineSyncJob: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-28 10:54:14.734  4185  4255 E OfflineSyncJob: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-28 10:54:14.734  4185  4255 E OfflineSyncJob: 	at java.lang.Thread.run(Thread.java:923)
08-28 10:54:14.742  4185  4213 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=c93c8311-956e-4402-947a-a802926fad96, tags={ timestamp:1630117417355, com.nextcloud.client.jobs.OfflineSyncWork, *, name:periodic_offline_sync } ]
08-28 10:54:14.752  1290  1761 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=26, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10159 AdministratorUids: [] RequestorUid: 10159 RequestorPackageName: com.nextcloud.client] ] (release request)
08-28 10:54:17.353  1827  1827 D KeyguardClockSwitch: Updating clock: 10:54
08-28 10:54:31.262  2572  2572 I wpa_supplicant: wlan0: WPA: Group rekeying completed with 94:83:c4:04:dc:f7 [GTK=TKIP]
08-28 10:54:31.483     0     0 I         : kworker/dying (85) used greatest stack depth: 10336 bytes left
08-28 10:54:37.555  2128  2128 D ServiceStateProvider: subId=1

```

## System

v11-1.1
LineageOS for microG 18.1 2021-08-11
FP3 (Fairphone 3)

## Important

It would be glad if you could soonish give me a hint about whether this is an issue that can be fixed, or whether I should reset the device I have installed and try the process again? Because until now, I do not have a lot of data restored and I would just do unnecessary work in case I need to reinstall it anyway…

## More…

Nothing works here… (after clearing the data)
```
$ adb shell bmgr list transports 
    com.android.localtransport/.LocalTransport

$ adb shell bmgr list transports -c
com.android.localtransport/.LocalTransportService

$ adb shell bmgr list sets         
Unable to request restore sets

$ adb shell bmgr backupnow --all
Running incremental backup for all packages.
Unable to run backup
Backup finished with result: Transport error
```

**Comment by grote** [comment]
Your log seems to suggest that Nextcloud is throwing a RuntimeException.

>  I use an external SD card formatted as "adopted storage" that always takes some seconds at startup until it is detected. Just in case that matters.

Potentially relevant: `08-28 10:47:02.449  3529  3529 F zygote64: jni_internal.cc:729] JNI FatalError called: (com.stevesoltys.seedvault) frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:795: Failed to mount tmpfs to /mnt/expand/2484f4fd-7758-4d04-9e4a-d77a886098f3/user: No such file or directory`

**Comment by rugk** [comment]
Oh thanks for your reply. So but what?

The backup restore actually did work (from Nextcloud and including the/onto the adoptable storage), it really just looks like a display bug in the settings.

I am alos quite shocked to see that clearing the data did not reset/change anything. :sweat_smile:

**Comment by rugk** [comment]
All in all, it seems only reinstallation will fix this… :cry:

**Comment by rugk** [comment]
Oh I get a well-known error in several apps. The reason is when I tried the original backup restore I did not use Nextcloud and instead tried to push my `.SeedVaultAndroidBackup` on my `/sdcard`. First via the file sharing of Android, then via `adb push`.

This somehow corrupted my file system (the adoptable storage?). Though, I have to say I can still use it, but e.g. if I try to delete that `.SeedVaultAndroidBackup` directory that fails. In the Android file manager or via adb:

```
$ rm -rf .SeedVaultAndroidBackup                                                                                                                                               
rm: 1630109228740: Directory not empty
```

Also, although data is there and clearly copied, it just cannot read it:
```
$ ls -la .SeedVaultAndroidBackup/1630109228740/                                                                                                                                  
total 0
```

from Threema:
```
java.io.IOException: Structure needs cleaning
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
	at java.io.File.createNewFile(File.java:1008)
	at ch.threema.app.utils.m0.b(SourceFile:1)
	at ch.threema.app.services.r1.b(SourceFile:37)
	at ch.threema.app.services.t2.W(SourceFile:47)
	at ch.threema.app.services.t2.M(SourceFile:190)
	at ch.threema.app.processors.b.a(SourceFile:82)
	at ch.threema.app.processors.b.b(SourceFile:75)
	at ch.threema.client.f1.d(SourceFile:60)
	at ch.threema.client.f1.run(SourceFile:83)
	at java.lang.Thread.run(Thread.java:923)

	
```

**Comment by rugk** [comment]
Okay wow, could "fix" the issue by moving "all" data to the internal storage (again the `.SeedVaultAndroidBackup` did not work of course – original size BTW just ~800MB, it's the same as on the Nextcloud), the formating the SD card as external storage and rebooting.

Now trying to format it as adoptable storage again. (Actually the sdcard is new, so I should not have destroyed so much :sweat_smile:)

**Comment by rugk** [comment]
For this to work on Android you must remove the SD card manually, delete the partition with some other device and then re-insert it, so Android does not mount it as an external storage (which you cannot convert to an adoptable one).

I can report after doing that (i.e. making it adoptable again and moving the data there), the menu entry is still there…
Now reboot…
Still there…

It seems indeed the broken FS/`.SeedVaultAndroidBackup` dir that actually caused this behaviour. Anyway, maybe you can improve the behavior in case of such a failure? Especially, as I actually did not actually use that backup from there, but from Nextcloud…

**Comment by rugk** [comment]
Oh no, now I restored the Threema backup again (~3GB) and now Threema broke with the same issue again and after one reboot also Seedvault disappears…

I highly doubt the sdcard has a hardware failure, or maybe the FS of Android just cannot handle so much data written (either big Seedvault backup or big Threema backup…)…

Just gonna switch to internal storage for now hmm…

**Comment by rugk** [comment]
Sooo… now restored the backup inside of internal storage with Threema and I have no idea what is going on. It again breaks the Threema's own media storage **and** Seedvault (it disappears from the menu).
It is again reproducible.

As soon as I then move the files from internal to sd card (after formatting the SD card as adopted storage), now both works again – except that I of course lost my old images in Threema.
I have no idea what's going on.

Do you think a system reset would help here? And if so, what should I try – with adoptable storage or without? And why is Threema causing this corruption? /cc @threema-maurus @threema-fabian and @threema-danilo/@dbrgn (internal beta tester ticket from 2021-08-28 14:18:03)

**Comment by rugk** [comment]
Oh no, damn it, it is apparently a hardware problem or at least Fairphone 3 problem:
https://forum.fairphone.com/t/android-10-microsd-as-phone-storage/64806/2?u=rugk
'
Sorry, y'all for disturbing you. Likely none of your apps have anything to do with that.

The only thing for Seedvault would be… and that is the only reason I leave this issue open… is to improve the error handling or so in such an IO failure. Maybe it can still allow to do backups… after all before doing a factory reset when such a thing happens, you likely want to **try** to backup your data…

(A workaround can be seen above, try to format the sd card as external again/move data into the internal storage) What still somewhat puzzles me though is why internal storage also has this problem now, but likeyl because it was connected and this si "infectious" or whatever… puhh… :disappointed:
